export enum ScreenNames {
  App = 'App',
  Auth = 'Auth',
  Root = 'Root',
  Home = 'Home',
  NoInternet = 'NoInternet',
  Splash = 'Splash',
  Profile = 'Profile',
  Notifications = 'Notifications',
  NotificationSettings = 'NotificationSettings',
  Search = 'Search',
  Leaderboard = 'Leaderboard',
  Feed = 'Feed',
  FeedDetail = 'FeedDetail',
  Upload = 'Upload',
  UploadTab = 'UploadTab',
  // NOTE: the DM list is mounted as `DM` (BottomTabNavigator). A second
  // `DirectMessages` entry used to exist here and silently broke push
  // notification routing — do not reintroduce an alias for a mounted screen.
  DM = 'DM',
  VideoPlayer = 'VideoPlayer',
  ImageViewer = 'ImageViewer',
  Chat = 'Chat',
  LiveProducer = 'LiveProducer',
  LiveViewer = 'LiveViewer',
  AccountSettings = 'AccountSettings',
  YourVideos = 'YourVideos',
  LikedVideos = 'LikedVideos',
  SavedPosts = 'SavedPosts',
  EditProfile = 'EditProfile',
  Dpay = 'Dpay',
  FollowList = 'FollowList',
  RepostQuoteList = 'RepostQuoteList',
  PrivacySettings = 'PrivacySettings',
  Drafts = 'Drafts',
  MyLibrary = 'MyLibrary',
  PostResolver = 'PostResolver',
  /** Same component as PostResolver — react-navigation allows one deep-link
   *  path per screen, and /newpost/:n needs its own. */
  PostResolverNewPost = 'PostResolverNewPost',
  LiveChat = 'LiveChat',
  LiveChatInfo = 'LiveChatInfo',
  FullscreenVideo = 'FullscreenVideo',
  AIChat = 'AIChat',
  Explore = 'Explore',
  UploadQueue = 'UploadQueue',
  ActiveSessions = 'ActiveSessions',
  ShortsViewer = 'ShortsViewer',
  ImageFeed = 'ImageFeed',
  // Calls and Stages are presented as app-wide modals (CallModalsHost /
  // StagesModalsHost in App.tsx), not routes — they deliberately have no
  // ScreenNames entry. Navigating to an unregistered name throws at runtime.
  Earnings = 'Earnings',
  Communities = 'Communities',
  CommunityDetail = 'CommunityDetail',
  CommunityInvite = 'CommunityInvite',
  Glossary = 'Glossary',
  Guide = 'Guide',
  Arcade = 'Arcade',
  ArcadeGame = 'ArcadeGame',
  Events = 'Events',
  Careers = 'Careers',
  Affiliate = 'Affiliate',
  // Comments expand inline in the card (as on web) — there is no detail route.
  FeatureRequests = 'FeatureRequests',
  Stores = 'Stores',
  StoreDetail = 'StoreDetail',
  ListingDetail = 'ListingDetail',
  CommandCentre = 'CommandCentre',
  Top100 = 'Top100',
  Ads = 'Ads',
  Prompt = 'Prompt',
  TV = 'TV',
  Work = 'Work',
  WorkJobDetail = 'WorkJobDetail',
  WorkPost = 'WorkPost',
  Governance = 'Governance',
  SuperPowers = 'SuperPowers',
  // Auth screens
  Onboarding = 'Onboarding',
  SignIn = 'SignIn',
  SetProfile = 'SetProfile',
  ImportWallet = 'ImportWallet',
}
