export enum ScreenNames {
  Test = 'Test',
  Root = 'Root',
  Home = 'Home',
  NoInternet = 'NoInternet',
  Splash = 'Splash',
  Profile = 'Profile',
  Settings = 'Settings',
  Notifications = 'Notifications',
  Search = 'Search',
  Leaderboard = 'Leaderboard',
  Feed = 'Feed',
  Upload = 'Upload',
  DM = 'DM',
  DirectMessages = 'DirectMessages',
  VideoPlayer = 'VideoPlayer',
  ImageViewer = 'ImageViewer',
  AccountSettings = 'AccountSettings',
  YourVideos = 'YourVideos',
  LikedVideos = 'LikedVideos',
  EditProfile = 'EditProfile',
  // Auth screen
  SignIn = 'SignIn',
}
