export enum ScreenNames {
  App = 'App',
  Auth = 'Auth',
  Root = 'Root',
  Home = 'Home',
  NoInternet = 'NoInternet',
  Splash = 'Splash',
  Profile = 'Profile',
  Notifications = 'Notifications',
  NotificationSettings = 'NotificationSettings',
  Search = 'Search',
  Leaderboard = 'Leaderboard',
  Stats = 'Stats',
  Feed = 'Feed',
  FeedDetail = 'FeedDetail',
  PostInfo = 'PostInfo',
  Upload = 'Upload',
  UploadTab = 'UploadTab',
  // NOTE: the DM list is mounted as `DM` (BottomTabNavigator). A second
  // `DirectMessages` entry used to exist here and silently broke push
  // notification routing — do not reintroduce an alias for a mounted screen.
  DM = 'DM',
  VideoPlayer = 'VideoPlayer',
  ImageViewer = 'ImageViewer',
  Chat = 'Chat',
  LiveProducer = 'LiveProducer',
  LiveViewer = 'LiveViewer',
  AccountSettings = 'AccountSettings',
  YourVideos = 'YourVideos',
  LikedVideos = 'LikedVideos',
  SavedPosts = 'SavedPosts',
  EditProfile = 'EditProfile',
  Dpay = 'Dpay',
  Dex = 'Dex',
  DexPool = 'DexPool',
  FollowList = 'FollowList',
  RepostQuoteList = 'RepostQuoteList',
  PrivacySettings = 'PrivacySettings',
  Drafts = 'Drafts',
  MyLibrary = 'MyLibrary',
  PostResolver = 'PostResolver',
  /** Same component as PostResolver — react-navigation allows one deep-link
   *  path per screen, and /newpost/:n needs its own. */
  PostResolverNewPost = 'PostResolverNewPost',
  LiveChat = 'LiveChat',
  LiveChatInfo = 'LiveChatInfo',
  FullscreenVideo = 'FullscreenVideo',
  AIChat = 'AIChat',
  Creator = 'Creator',
  // Creator Flow — your flows (/creator/flow) and one flow (/creator/flow/:id).
  CreatorFlow = 'CreatorFlow',
  CreatorFlowView = 'CreatorFlowView',
  MediaEditor = 'MediaEditor',
  Explore = 'Explore',
  UploadQueue = 'UploadQueue',
  ActiveSessions = 'ActiveSessions',
  TvRequests = 'TvRequests',
  SignInTv = 'SignInTv',
  ShortsViewer = 'ShortsViewer',
  ImageFeed = 'ImageFeed',
  // Stages discovery is a screen; only the live room and the create form are
  // modals (StagesModalsHost in App.tsx), the same split web has between
  // /stages and its persistent AudioSpacesModal.
  Stages = 'Stages',
  // Calls are presented as an app-wide modal (CallModalsHost in App.tsx), not a
  // route — they deliberately have no ScreenNames entry. Navigating to an
  // unregistered name throws at runtime.
  Earnings = 'Earnings',
  Communities = 'Communities',
  CommunityDetail = 'CommunityDetail',
  CommunityInvite = 'CommunityInvite',
  Converter = 'Converter',
  Migrate = 'Migrate',
  Glossary = 'Glossary',
  Guide = 'Guide',
  // Connect AI — the hub (/connect) and one guide per assistant. The two
  // guides share a component; the route name says which assistant.
  Connect = 'Connect',
  ConnectChatGPT = 'ConnectChatGPT',
  ConnectClaude = 'ConnectClaude',
  Arcade = 'Arcade',
  ArcadeGame = 'ArcadeGame',
  ArcadeChessOnline = 'ArcadeChessOnline',
  Events = 'Events',
  Careers = 'Careers',
  // Prize draws explainer — dehub.io/raffle.
  Raffle = 'Raffle',
  // Where to watch any film or series — dehub.io/cinema[/film|series/:id].
  Cinema = 'Cinema',
  // The creator application form — dehub.io/creators.
  Creators = 'Creators',
  // Plan pages. Buying happens on the website, and only where Google Play
  // allows linking out to it — see hooks/useWebCheckout.
  Premium = 'Premium',
  Pricing = 'Pricing',
  Affiliate = 'Affiliate',
  // Comments expand inline in the card (as on web) — there is no detail route.
  FeatureRequests = 'FeatureRequests',
  Usernames = 'Usernames',
  Fractions = 'Fractions',
  Accounts = 'Accounts',
  Stores = 'Stores',
  StoreDetail = 'StoreDetail',
  ListingDetail = 'ListingDetail',
  CommandCentre = 'CommandCentre',
  Top100 = 'Top100',
  Agents = 'Agents',
  Ads = 'Ads',
  Prompt = 'Prompt',
  TV = 'TV',
  Work = 'Work',
  WorkJobDetail = 'WorkJobDetail',
  WorkPost = 'WorkPost',
  WorkEdit = 'WorkEdit',
  WorkHistory = 'WorkHistory',
  WorkDisputes = 'WorkDisputes',
  Governance = 'Governance',
  GovernanceProposal = 'GovernanceProposal',
  Dao = 'Dao',
  SuperPowers = 'SuperPowers',
  // Creator packs (emoji, sticker and GIF) — the hub and one pack's share page.
  Packs = 'Packs',
  Pack = 'Pack',
  // Builder — describe an app, AI writes and hosts it; the preview is public.
  Builder = 'Builder',
  BuilderProject = 'BuilderProject',
  BuilderPreview = 'BuilderPreview',
  DePin = 'DePin',
  Bridge = 'Bridge',
  // Launchpad — the coin list, one coin, and the create flow.
  Launchpad = 'Launchpad',
  LaunchpadCoin = 'LaunchpadCoin',
  LaunchpadCreate = 'LaunchpadCreate',
  // Auth screens
  Onboarding = 'Onboarding',
  SignIn = 'SignIn',
  SetProfile = 'SetProfile',
  ImportWallet = 'ImportWallet',
}
