import { Platform } from "react-native";
import env from "../../config/env";
import { storage } from "../storage";

/**
 * Emoji picker data: the full Unicode set, keyword search in the viewer's
 * language, skin tones, recents and an OS-version gate so the sheet never
 * offers an emoji this phone draws as a blank box.
 *
 * data/ is generated by dehubweb's scripts/build-emoji-data.mjs (run it with
 * `--mobile <this repo>`); never edit it by hand. English keywords ship in the
 * bundle as the offline fallback. Every other language's keywords are fetched
 * once from the web app's versioned /emoji-data/ path and kept in MMKV.
 */

export type EmojiGroup =
  | "smileys"
  | "people"
  | "animals"
  | "food"
  | "travel"
  | "activities"
  | "objects"
  | "symbols"
  | "flags";

export interface EmojiEntry {
  i: number;
  char: string;
  group: EmojiGroup;
  /** Unicode Emoji version ×10. */
  v: number;
  skins?: string[];
  skinV?: number;
  /** Noto animated codepoint, when Google publishes an animated version. */
  anim?: string;
}

export interface EmojiKeywords {
  labels: string[];
  search: string[];
}

type RawRow = [string, number, number, string[]?, number?];
interface RawDataset {
  version: string;
  groups: EmojiGroup[];
  emoji: RawRow[];
  animated: Record<string, string>;
}

/** Same row as dehubweb's picker, in the same order. */
export const DEHUB_PICKS = [
  "🚀", "💎", "🙌", "🔥", "💯", "🫡", "👀", "🤝",
  "🧠", "🌕", "📈", "📉", "🐂", "🐻", "🐋", "🦍",
  "💰", "🪙", "🤑", "🏆", "👑", "⚡", "🎯", "🔫",
  "🎮", "🎬", "🫶", "😤", "💀", "🤡", "🗿", "🥶",
];

export const SKIN_TONE_SWATCHES = ["✋", "✋🏻", "✋🏼", "✋🏽", "✋🏾", "✋🏿"] as const;
export type SkinTone = 0 | 1 | 2 | 3 | 4 | 5;

/**
 * Newest Unicode Emoji version (×10) the system font draws. Android follows
 * the platform release; iOS follows the point release that shipped each set.
 */
export function maxEmojiVersion(): number {
  if (Platform.OS === "android") {
    const api = typeof Platform.Version === "number" ? Platform.Version : Number(Platform.Version);
    if (api >= 36) return 160;
    if (api >= 35) return 151;
    if (api >= 34) return 150;
    if (api >= 33) return 140;
    if (api >= 31) return 131;
    if (api >= 30) return 130;
    if (api >= 29) return 120;
    if (api >= 28) return 110;
    return 50;
  }
  if (Platform.OS === "ios") {
    const [major, minor = 0] = String(Platform.Version).split(".").map(Number);
    const at = (M: number, m: number) => major > M || (major === M && minor >= m);
    if (at(26, 4)) return 170;
    if (at(18, 4)) return 160;
    if (at(17, 4)) return 151;
    if (at(16, 4)) return 150;
    if (at(15, 4)) return 140;
    if (at(14, 5)) return 131;
    if (at(14, 2)) return 130;
    if (at(13, 2)) return 121;
    if (at(12, 1)) return 110;
    return 50;
  }
  return 1000;
}

export interface EmojiDataset {
  version: string;
  groups: EmojiGroup[];
  entries: EmojiEntry[];
  byChar: Map<string, EmojiEntry>;
  /** Locale → keyword file name. */
  locales: Record<string, string>;
}

let dataset: EmojiDataset | null = null;

/** Parsed on first open, not at boot — the require sits inside the call. */
export function getEmojiData(): EmojiDataset {
  if (dataset) return dataset;
  const raw = require("./data/emoji.json") as RawDataset;
  const locales = require("./data/locales.json") as Record<string, string>;
  const entries: EmojiEntry[] = raw.emoji.map(([char, g, v, skins, skinV], i) => ({
    i,
    char,
    group: raw.groups[g],
    v,
    skins,
    skinV: skins ? skinV ?? v : undefined,
    anim: raw.animated[String(i)],
  }));
  const byChar = new Map<string, EmojiEntry>();
  for (const e of entries) {
    byChar.set(e.char, e);
    byChar.set(e.char.replace(/️/g, ""), e);
  }
  dataset = { version: raw.version, groups: raw.groups, entries, byChar, locales };
  return dataset;
}

function parseKeywords(rows: unknown): EmojiKeywords | null {
  if (!Array.isArray(rows)) return null;
  const labels: string[] = [];
  const search: string[] = [];
  for (const row of rows) {
    if (typeof row !== "string") return null;
    const bar = row.indexOf("|");
    labels.push(row.slice(0, bar));
    search.push(` ${row.slice(bar + 1)}`);
  }
  return { labels, search };
}

let englishKeywords: EmojiKeywords | null = null;

export function getEnglishKeywords(): EmojiKeywords {
  englishKeywords ??= parseKeywords(require("./data/names-en.json")) ?? { labels: [], search: [] };
  return englishKeywords;
}

const inflight = new Map<string, Promise<EmojiKeywords | null>>();

/** The viewer's language, from MMKV or fetched once from the web app. Null when English or offline. */
export function loadLocalKeywords(locale: string): Promise<EmojiKeywords | null> {
  const data = getEmojiData();
  const base = locale.toLowerCase().split("-")[0];
  const file = data.locales[locale] ?? data.locales[base];
  if (!file || file === "en") return Promise.resolve(null);

  const key = `emoji:names:${data.version}:${file}`;
  const cached = storage.getString(key);
  if (cached) {
    try {
      const parsed = parseKeywords(JSON.parse(cached));
      if (parsed && parsed.labels.length === data.entries.length) return Promise.resolve(parsed);
    } catch {
      /* re-fetch below */
    }
  }

  let p = inflight.get(key);
  if (!p) {
    const origin = (env.APP_ORIGIN || "https://dehub.io").replace(/\/$/, "");
    p = fetch(`${origin}/emoji-data/${data.version}/names/${file}.json`)
      .then((res) => (res.ok ? res.text() : null))
      .then((text) => {
        if (!text) return null;
        // The web SPA answers a missing file with index.html and a 200.
        const parsed = parseKeywords(JSON.parse(text));
        if (!parsed || parsed.labels.length !== data.entries.length) return null;
        storage.set(key, text);
        return parsed;
      })
      .catch(() => null)
      .finally(() => inflight.delete(key));
    inflight.set(key, p);
  }
  return p;
}

/** Every query word must start one of the emoji's keywords. Label matches rank first. */
export function searchEmoji(
  query: string,
  entries: EmojiEntry[],
  keywords: Array<EmojiKeywords | null>,
  limit = 240,
): EmojiEntry[] {
  const q = query.trim().toLowerCase().replace(/^:|:$/g, "");
  if (!q) return [];
  const tokens = q.split(/\s+/).map((t) => ` ${t}`);
  const lists = keywords.filter((k): k is EmojiKeywords => !!k);
  const scored: Array<[number, EmojiEntry]> = [];
  for (const e of entries) {
    if (e.char === query.trim()) {
      scored.push([-1, e]);
      continue;
    }
    let best = Infinity;
    for (const k of lists) {
      const hay = k.search[e.i];
      if (!hay || !tokens.every((t) => hay.includes(t))) continue;
      const label = k.labels[e.i]?.toLowerCase() ?? "";
      const score = label === q ? 0 : label.startsWith(q) ? 1 : 2;
      if (score < best) best = score;
    }
    if (best !== Infinity) scored.push([best, e]);
  }
  scored.sort((a, b) => a[0] - b[0] || a[1].i - b[1].i);
  return scored.slice(0, limit).map(([, e]) => e);
}

export function withTone(e: EmojiEntry, tone: SkinTone, maxV: number): string {
  if (!tone || !e.skins || (e.skinV ?? e.v) > maxV) return e.char;
  return e.skins[tone - 1];
}

export function animatedUrl(code: string) {
  return `https://fonts.gstatic.com/s/e/notoemoji/latest/${code}/512.webp`;
}

const TONE_KEY = "dehub:emoji:tone";
const RECENT_KEY = "dehub:emoji:recent";
const RECENT_MAX = 32;

export function readSkinTone(): SkinTone {
  const n = storage.getNumber(TONE_KEY) ?? 0;
  return (n >= 0 && n <= 5 ? n : 0) as SkinTone;
}

export function writeSkinTone(tone: SkinTone) {
  storage.set(TONE_KEY, tone);
}

/** Base emoji, so a later tone change re-tints them. */
export function readRecents(): string[] {
  try {
    const raw = JSON.parse(storage.getString(RECENT_KEY) || "[]");
    return Array.isArray(raw) ? raw.filter((s): s is string => typeof s === "string").slice(0, RECENT_MAX) : [];
  } catch {
    return [];
  }
}

export function pushRecent(base: string): string[] {
  const next = [base, ...readRecents().filter((c) => c !== base)].slice(0, RECENT_MAX);
  storage.set(RECENT_KEY, JSON.stringify(next));
  return next;
}
