declare module '@env' {
    export const API_URL: string;
    export const APP_ENV: string;
    export const INFURA_KEY: string;
    export const ALCHEMY_API_KEY: string;
    export const WEB3AUTH_CLIENT_ID: string;
    export const WEB3AUTH_APPLE_VERIFIER: string;
    export const CDN_BASE_URL: string;
    export const APP_ORIGIN: string;
    export const REOWN_PROJECT_ID: string;
    export const WEBSOCKET_URL: string;
    export const LIVEPEER_API_KEY: string;
    export const DEBUG: string;
    export const AUTH_PROVIDER: string;
    export const TENOR_API_KEY: string;
    export const STRIPE_PUBLISHABLE_KEY: string;
    export const LEGACY_APP_ORIGIN: string;
    export const SUPABASE_EDGE_BASE_URL: string;
    export const SUPABASE_URL: string;
    export const SUPABASE_PUBLISHABLE_KEY: string;
    export const AGORA_APP_ID: string;
}