import { act, cleanup, renderHook } from "@testing-library/react-native";
import { useProjectHistory } from "../../libs/editor/useProjectHistory";
import { cloudDraftHistoryEditor } from "../../libs/editor/cloudDraftHistoryEditor";
import { cloudDraftController, type CloudDraftControllerState, type CloudLiveSession } from "../../libs/editor/cloudDraftController";
import type { ProjectSnapshot } from "../../libs/editor/types";
jest.mock("react-native-css-interop",()=>({createInteropElement:require("react").createElement}));
const wallet="0x"+"a".repeat(40);
const fixture=():ProjectSnapshot=>({id:"device",title:"Film",updatedAt:1,settings:{width:1920,height:1080,fps:30,aspectPreset:"16:9",background:"#000"},tracks:[{id:"v",kind:"video",name:"Video",muted:false,hidden:false}],
  clips:[{id:"a",kind:"video",trackId:"v",mediaId:"source",start:0,trimIn:0,duration:5},{id:"b",kind:"video",trackId:"v",mediaId:"source",start:5,trimIn:0,duration:5}]});
const copy=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
const controllers:ReturnType<typeof cloudDraftController>[]=[];
beforeEach(()=>jest.useFakeTimers());afterEach(()=>{for(const controller of controllers.splice(0))controller.stop();cleanup();jest.useRealTimers();});
async function tick(ms=0){await act(async()=>{jest.advanceTimersByTime(ms);for(let i=0;i<40;i++)await Promise.resolve();});}
function setup(){const hook=renderHook(()=>useProjectHistory(fixture())),states:CloudDraftControllerState[]=[];const session:CloudLiveSession={recoverLiveProject:jest.fn(async()=>{}),receiveLiveProject:jest.fn(async(_snapshot,_accept,check)=>{check();}),publishLiveProject:jest.fn(async(_snapshot,check)=>{check();return true;})};const controller=cloudDraftController(wallet,"device",session,cloudDraftHistoryEditor(hook.result.current),{check:()=>{},update:state=>states.push(state)});controllers.push(controller);return {hook,controller,session,states};}
describe("live controller using the actual native history adapter",()=>{
  it("waits for a real canvas gesture and publishes the settled result once",async()=>{const e=setup();e.controller.start(true);await tick();act(()=>{const first=fixture();first.clips[0].start=1;e.hook.result.current.live(first);const second=fixture();second.clips[0].start=2;e.hook.result.current.live(second);});await tick(5000);expect(e.session.publishLiveProject).toHaveBeenCalledTimes(1);act(()=>e.hook.result.current.settle());await tick(700);expect(e.session.publishLiveProject).toHaveBeenCalledTimes(2);expect(jest.mocked(e.session.publishLiveProject).mock.calls[1][0].clips[0].start).toBe(2);act(()=>e.hook.result.current.undo());expect(e.hook.result.current.latest()?.clips[0].start).toBe(0);expect(e.hook.result.current.canUndo).toBe(false);});
  it("waits for every overlapping asynchronous command lease",async()=>{const e=setup();e.controller.start(true);await tick();let first!:NonNullable<ReturnType<typeof e.hook.result.current.holdEdits>>,second!:typeof first;act(()=>{first=e.hook.result.current.holdEdits()!;second=e.hook.result.current.holdEdits()!;const next=fixture();next.title="Latest";e.hook.result.current.commit(next);first.release();});await tick(5000);expect(e.session.publishLiveProject).toHaveBeenCalledTimes(1);act(()=>second.release());await tick(700);expect(e.session.publishLiveProject).toHaveBeenCalledTimes(2);});
  it("retains local Undo and Redo across an incoming edit without a receive-only step",async()=>{const e=setup();act(()=>{const one=fixture();one.title="One";e.hook.result.current.commit(one);const two=fixture();two.title="Two";e.hook.result.current.commit(two);e.hook.result.current.undo();});jest.mocked(e.session.receiveLiveProject).mockImplementationOnce(async(snapshot,accept,check)=>{check();const incoming=copy(snapshot);incoming.clips[1].duration=4;accept(incoming);});e.controller.start(false);await tick();expect(e.hook.result.current.canUndo).toBe(true);expect(e.hook.result.current.canRedo).toBe(true);act(()=>e.hook.result.current.redo());expect(e.hook.result.current.latest()?.title).toBe("Two");act(()=>{e.hook.result.current.undo();e.hook.result.current.undo();});expect(e.hook.result.current.latest()?.title).toBe("Film");expect(e.hook.result.current.latest()?.clips[1].duration).toBe(4);expect(e.hook.result.current.canUndo).toBe(false);expect(e.session.publishLiveProject).not.toHaveBeenCalled();});
  it("stops consent on a same-ID reset through the actual native observer",async()=>{const e=setup();e.controller.start(true);act(()=>e.hook.result.current.reset(fixture()));await tick(5000);expect(e.session.receiveLiveProject).not.toHaveBeenCalled();expect(e.states[e.states.length-1].mode).toBeNull();});
  it("unsubscribes the actual history observer when Stop is requested",async()=>{const e=setup();e.controller.start(true);await tick();e.controller.stop();act(()=>{const next=fixture();next.title="Private";e.hook.result.current.commit(next);});await tick(5000);expect(e.session.publishLiveProject).toHaveBeenCalledTimes(1);expect(jest.getTimerCount()).toBe(0);});
});
