// Cross-client parity for the wallet crypto core.
//
// The point of these tests is NOT that mobile can open its own output — that
// would pass even if both sides of this port were wrong together. It is that
// mobile opens payloads produced by the WEB client, whose implementation uses
// entirely different primitives (hash-wasm Argon2id + WebCrypto AES-GCM vs
// @noble pure JS). Every WEB_* vector below was generated by running
// dehubweb/src/lib/wallet-core/crypto.ts.
//
// If these fail, cross-device access to real wallets is broken — a wallet
// created on the web would no longer open on the phone. Regenerate the vectors
// only when the web payload format itself intentionally changes.
//
// ON COST: Argon2id parameters travel inside each payload's header, so a vector
// written with cheap parameters exercises byte-for-byte the same decrypt path as
// a production one. Most tests use WEB_ARGON2ID_CHEAP for that reason. The two
// marked "production parameters" deliberately pay the real cost — they are the
// canaries that would catch a parameter mismatch the cheap vectors cannot see.
import {
  decryptString,
  decryptStringWithKeyMaterial,
  encryptString,
  encryptStringWithKeyMaterial,
  isLegacyPayload,
  type EncryptedPayload,
} from "../../libs/wallet-core/crypto";

// expo-crypto is a native module; jest cannot load it. Only encryption needs
// randomness, and these bytes never have to be unpredictable for a test.
jest.mock("expo-crypto", () => ({
  getRandomBytes: (n: number) =>
    Uint8Array.from({ length: n }, (_, i) => (i * 37 + 11) & 0xff),
}));

const SEED =
  "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
const PASSWORD = "correct horse battery staple";

// Written by the web client at PRODUCTION parameters (m=65536, t=3, p=1).
const WEB_ARGON2ID: EncryptedPayload = {
  ciphertext:
    "v2:eyJrZGYiOiJhcmdvbjJpZCIsIm0iOjY1NTM2LCJ0IjozLCJwIjoxfQ:0iXudctXDyxfOiG6lIohiKN37uwxGn2Peokt7HndFG4UoZXaHkJuTxchHd96BZVwqWTO/x1a6pOwZB1O0UM/K8L+0g4i+QKLtrBi3YhRuhE307SiUzmR4Rt5GjoCJE9JHTTEnj309lz0hHX8yA==",
  salt: "7Cq1jGUvQrmq1V/94Sl/zA==",
  iv: "BMKYMImYQPs8wgK5",
  iterations: 0,
};

// Same client, same primitives, cheap parameters (m=1024, t=1, p=1).
const WEB_ARGON2ID_CHEAP: EncryptedPayload = {
  ciphertext:
    "v2:eyJrZGYiOiJhcmdvbjJpZCIsIm0iOjEwMjQsInQiOjEsInAiOjF9:Jf0vR8D9da9nuyflvYtK6uDy4rh5O6CbYRqrr8BuaIZetOSy4G5ESpGgmzlIn4O5CtoEmKa2zJQlOd2ZMQnmOI6GThwSqtE97jLfp5tDeMuyfz+FVvVI5iCWBa2EHzNAyjGvldccMuFaofgvvA==",
  salt: "HJKC4fy8IwhsEcVT/IEoTQ==",
  iv: "jnJy1XcLhh7xQ7W4",
  iterations: 0,
};

const WEB_HKDF: EncryptedPayload = {
  ciphertext:
    "v2:eyJrZGYiOiJoa2RmIiwiaCI6IlNIQS0yNTYifQ:vdNNRlszK4flATFKv5acvp6Kq32VG2mtAWyvdyYPgpMu0NZCoxPo47yoPS5n0Fk9jscx98L72eg+1Kyl95uDEIFG8GOtava3PHsxI3bUN06GrrXTECqxeMESZIJ6QZOTatrMJBeGVli7HpRn6Q==",
  salt: "Z+EPdmuUEi6kj7gW1SJVVg==",
  iv: "B7GvGcfUBdYXJp4t",
  iterations: 0,
};

const WEB_KEY_MATERIAL = new Uint8Array([
  5, 16, 27, 38, 49, 60, 71, 82, 93, 104, 115, 126, 137, 148, 159, 170, 181, 192, 203, 214, 225,
  236, 247, 2, 13, 24, 35, 46, 57, 68, 79, 90,
]);

// Legacy PBKDF2, as written before the Argon2id upgrade: no v2 prefix, the
// iteration count lives in the row.
const WEB_LEGACY_PBKDF2: EncryptedPayload = {
  ciphertext:
    "rzryyy7y5A2tS89VI6vBMs60sHEgAepKxa63XRyM67DL6Q5KlaCIfgg01t0XNWvAZUxeLRq8XVDT2GQkwXMPxQQAHmAecS42jYW5BRZZRHu1av1mVS03G1dKvkloD+xtTmK2cSUcjapnQHF5Bw==",
  salt: "omul+GyoxPXKY0z6VF7FMw==",
  iv: "OVAtvtmw0PwwUdKD",
  iterations: 600000,
};

// Production Argon2id under ts-jest's instrumentation runs far slower than in a
// release build — roughly 100s per derivation here versus ~4s in plain Node.
const PRODUCTION_COST = 600_000;

describe("wallet-core/crypto — opens web-written payloads", () => {
  it("decrypts an Argon2id wallet created on the web", async () => {
    expect(await decryptString(WEB_ARGON2ID_CHEAP, PASSWORD)).toBe(SEED);
  });

  it("decrypts a legacy PBKDF2 wallet created on the web", async () => {
    expect(isLegacyPayload(WEB_LEGACY_PBKDF2)).toBe(true);
    expect(await decryptString(WEB_LEGACY_PBKDF2, PASSWORD)).toBe(SEED);
  }, 60_000);

  it("decrypts an HKDF-wrapped wallet created on the web", async () => {
    expect(await decryptStringWithKeyMaterial(WEB_HKDF, WEB_KEY_MATERIAL)).toBe(SEED);
  });

  it("decrypts a web wallet at production parameters", async () => {
    expect(await decryptString(WEB_ARGON2ID, PASSWORD)).toBe(SEED);
  }, PRODUCTION_COST);
});

describe("wallet-core/crypto — format it writes", () => {
  it("writes a payload the web client can read, at production parameters", async () => {
    const payload = await encryptString(SEED, PASSWORD);
    // Same header bytes as the web client emits => the web client will select
    // the same KDF and parameters when it reads this row.
    expect(payload.ciphertext.split(":")[1]).toBe(WEB_ARGON2ID.ciphertext.split(":")[1]);
    expect(payload.iterations).toBe(0);
    expect(await decryptString(payload, PASSWORD)).toBe(SEED);
  }, PRODUCTION_COST);

  it("round-trips its own HKDF output", async () => {
    const payload = await encryptStringWithKeyMaterial(SEED, WEB_KEY_MATERIAL);
    expect(await decryptStringWithKeyMaterial(payload, WEB_KEY_MATERIAL)).toBe(SEED);
  });
});

describe("wallet-core/crypto — refuses to guess", () => {
  it("rejects a wrong password without revealing anything", async () => {
    await expect(decryptString(WEB_ARGON2ID_CHEAP, "wrong password")).rejects.toThrow(
      /Incorrect password or corrupted data/,
    );
  });

  it("does not treat a biometric payload as a password payload", async () => {
    await expect(decryptString(WEB_HKDF, PASSWORD)).rejects.toThrow(/passkey-protected/i);
  });

  it("does not treat a password payload as a biometric payload", async () => {
    await expect(
      decryptStringWithKeyMaterial(WEB_ARGON2ID_CHEAP, WEB_KEY_MATERIAL),
    ).rejects.toThrow(/password, not biometrics/);
  });

  it("rejects short key material rather than encrypting weakly", async () => {
    await expect(encryptStringWithKeyMaterial(SEED, new Uint8Array(16))).rejects.toThrow(
      /too short/,
    );
  });

  it("distinguishes an unknown KDF from corruption", async () => {
    const future: EncryptedPayload = {
      ...WEB_ARGON2ID_CHEAP,
      ciphertext: `v2:${Buffer.from(JSON.stringify({ kdf: "kyber" }), "utf8").toString(
        "base64url",
      )}:AAAA`,
    };
    await expect(decryptString(future, PASSWORD)).rejects.toThrow(/newer version of DeHub/);
  });

  it("reports a truncated header as corruption", async () => {
    await expect(
      decryptString({ ...WEB_ARGON2ID_CHEAP, ciphertext: "v2:notbase64" }, PASSWORD),
    ).rejects.toThrow(/Corrupted wallet payload/);
  });
});
