import React from 'react';
import { SvgXml } from 'react-native-svg';
import icons from './icons.json';

export type TrenchstarIconName = keyof typeof icons;
/** Shared vector artwork generated by the web icon source. */
export function TrenchstarIcon({ name, size = 24 }: { name: TrenchstarIconName; size?: number }) {
  return <SvgXml xml={icons[name]} width={size} height={size} accessible={false} />;
}
