// Generated by scripts/icons-registry.js (`npm run icons:write`). Do not edit by hand.
//
// Only these icons are bundled. Importing each icon's own file, rather than
// anything from the package root, keeps the other ~1,600 out of the bundle.
import type { LucideIcon } from "lucide-react-native";
import ActivityIcon from "lucide-react-native/dist/esm/icons/activity";
import AlignCenterIcon from "lucide-react-native/dist/esm/icons/align-center";
import AlignLeftIcon from "lucide-react-native/dist/esm/icons/align-left";
import AlignRightIcon from "lucide-react-native/dist/esm/icons/align-right";
import AnchorIcon from "lucide-react-native/dist/esm/icons/anchor";
import AppleIcon from "lucide-react-native/dist/esm/icons/apple";
import ArchiveIcon from "lucide-react-native/dist/esm/icons/archive";
import ArrowDownIcon from "lucide-react-native/dist/esm/icons/arrow-down";
import ArrowDownLeftIcon from "lucide-react-native/dist/esm/icons/arrow-down-left";
import ArrowDownToLineIcon from "lucide-react-native/dist/esm/icons/arrow-down-to-line";
import ArrowLeftIcon from "lucide-react-native/dist/esm/icons/arrow-left";
import ArrowLeftRightIcon from "lucide-react-native/dist/esm/icons/arrow-left-right";
import ArrowRightIcon from "lucide-react-native/dist/esm/icons/arrow-right";
import ArrowUpIcon from "lucide-react-native/dist/esm/icons/arrow-up";
import ArrowUpDownIcon from "lucide-react-native/dist/esm/icons/arrow-up-down";
import ArrowUpLeftIcon from "lucide-react-native/dist/esm/icons/arrow-up-left";
import ArrowUpRightIcon from "lucide-react-native/dist/esm/icons/arrow-up-right";
import ArrowUpToLineIcon from "lucide-react-native/dist/esm/icons/arrow-up-to-line";
import AtSignIcon from "lucide-react-native/dist/esm/icons/at-sign";
import AtomIcon from "lucide-react-native/dist/esm/icons/atom";
import AudioLinesIcon from "lucide-react-native/dist/esm/icons/audio-lines";
import AwardIcon from "lucide-react-native/dist/esm/icons/award";
import BabyIcon from "lucide-react-native/dist/esm/icons/baby";
import BanIcon from "lucide-react-native/dist/esm/icons/ban";
import BanknoteIcon from "lucide-react-native/dist/esm/icons/banknote";
import BellIcon from "lucide-react-native/dist/esm/icons/bell";
import BellOffIcon from "lucide-react-native/dist/esm/icons/bell-off";
import BellRingIcon from "lucide-react-native/dist/esm/icons/bell-ring";
import BitcoinIcon from "lucide-react-native/dist/esm/icons/bitcoin";
import BlendIcon from "lucide-react-native/dist/esm/icons/blend";
import BoldIcon from "lucide-react-native/dist/esm/icons/bold";
import BookOpenIcon from "lucide-react-native/dist/esm/icons/book-open";
import BookmarkIcon from "lucide-react-native/dist/esm/icons/bookmark";
import BotIcon from "lucide-react-native/dist/esm/icons/bot";
import BriefcaseIcon from "lucide-react-native/dist/esm/icons/briefcase";
import BugIcon from "lucide-react-native/dist/esm/icons/bug";
import CalendarIcon from "lucide-react-native/dist/esm/icons/calendar";
import CalendarCheckIcon from "lucide-react-native/dist/esm/icons/calendar-check";
import CalendarClockIcon from "lucide-react-native/dist/esm/icons/calendar-clock";
import CalendarDaysIcon from "lucide-react-native/dist/esm/icons/calendar-days";
import CameraIcon from "lucide-react-native/dist/esm/icons/camera";
import CaseUpperIcon from "lucide-react-native/dist/esm/icons/case-upper";
import ChartBarBigIcon from "lucide-react-native/dist/esm/icons/chart-bar-big";
import ChartColumnIcon from "lucide-react-native/dist/esm/icons/chart-column";
import ChartNoAxesColumnIcon from "lucide-react-native/dist/esm/icons/chart-no-axes-column";
import ChartNoAxesCombinedIcon from "lucide-react-native/dist/esm/icons/chart-no-axes-combined";
import ChartPieIcon from "lucide-react-native/dist/esm/icons/chart-pie";
import CheckIcon from "lucide-react-native/dist/esm/icons/check";
import CheckCheckIcon from "lucide-react-native/dist/esm/icons/check-check";
import ChevronDownIcon from "lucide-react-native/dist/esm/icons/chevron-down";
import ChevronLeftIcon from "lucide-react-native/dist/esm/icons/chevron-left";
import ChevronRightIcon from "lucide-react-native/dist/esm/icons/chevron-right";
import ChevronUpIcon from "lucide-react-native/dist/esm/icons/chevron-up";
import ChevronsRightIcon from "lucide-react-native/dist/esm/icons/chevrons-right";
import CircleIcon from "lucide-react-native/dist/esm/icons/circle";
import CircleAlertIcon from "lucide-react-native/dist/esm/icons/circle-alert";
import CircleCheckIcon from "lucide-react-native/dist/esm/icons/circle-check";
import CircleCheckBigIcon from "lucide-react-native/dist/esm/icons/circle-check-big";
import CircleMinusIcon from "lucide-react-native/dist/esm/icons/circle-minus";
import CirclePlayIcon from "lucide-react-native/dist/esm/icons/circle-play";
import CircleXIcon from "lucide-react-native/dist/esm/icons/circle-x";
import ClapperboardIcon from "lucide-react-native/dist/esm/icons/clapperboard";
import ClipboardIcon from "lucide-react-native/dist/esm/icons/clipboard";
import ClipboardPasteIcon from "lucide-react-native/dist/esm/icons/clipboard-paste";
import ClockIcon from "lucide-react-native/dist/esm/icons/clock";
import CloudUploadIcon from "lucide-react-native/dist/esm/icons/cloud-upload";
import CoinsIcon from "lucide-react-native/dist/esm/icons/coins";
import CompassIcon from "lucide-react-native/dist/esm/icons/compass";
import ComponentIcon from "lucide-react-native/dist/esm/icons/component";
import CopyIcon from "lucide-react-native/dist/esm/icons/copy";
import CornerDownLeftIcon from "lucide-react-native/dist/esm/icons/corner-down-left";
import CpuIcon from "lucide-react-native/dist/esm/icons/cpu";
import CreditCardIcon from "lucide-react-native/dist/esm/icons/credit-card";
import CropIcon from "lucide-react-native/dist/esm/icons/crop";
import CrosshairIcon from "lucide-react-native/dist/esm/icons/crosshair";
import CrownIcon from "lucide-react-native/dist/esm/icons/crown";
import DeleteIcon from "lucide-react-native/dist/esm/icons/delete";
import Disc3Icon from "lucide-react-native/dist/esm/icons/disc-3";
import DollarSignIcon from "lucide-react-native/dist/esm/icons/dollar-sign";
import DownloadIcon from "lucide-react-native/dist/esm/icons/download";
import EllipsisIcon from "lucide-react-native/dist/esm/icons/ellipsis";
import EllipsisVerticalIcon from "lucide-react-native/dist/esm/icons/ellipsis-vertical";
import ExpandIcon from "lucide-react-native/dist/esm/icons/expand";
import ExternalLinkIcon from "lucide-react-native/dist/esm/icons/external-link";
import EyeIcon from "lucide-react-native/dist/esm/icons/eye";
import EyeOffIcon from "lucide-react-native/dist/esm/icons/eye-off";
import FacebookIcon from "lucide-react-native/dist/esm/icons/facebook";
import FastForwardIcon from "lucide-react-native/dist/esm/icons/fast-forward";
import FileIcon from "lucide-react-native/dist/esm/icons/file";
import FileTextIcon from "lucide-react-native/dist/esm/icons/file-text";
import FilmIcon from "lucide-react-native/dist/esm/icons/film";
import FingerprintIcon from "lucide-react-native/dist/esm/icons/fingerprint";
import FlagIcon from "lucide-react-native/dist/esm/icons/flag";
import FlameIcon from "lucide-react-native/dist/esm/icons/flame";
import FlipHorizontal2Icon from "lucide-react-native/dist/esm/icons/flip-horizontal-2";
import FlipVertical2Icon from "lucide-react-native/dist/esm/icons/flip-vertical-2";
import FolderIcon from "lucide-react-native/dist/esm/icons/folder";
import FolderInputIcon from "lucide-react-native/dist/esm/icons/folder-input";
import FolderPlusIcon from "lucide-react-native/dist/esm/icons/folder-plus";
import ForwardIcon from "lucide-react-native/dist/esm/icons/forward";
import FuelIcon from "lucide-react-native/dist/esm/icons/fuel";
import FullscreenIcon from "lucide-react-native/dist/esm/icons/fullscreen";
import FunnelIcon from "lucide-react-native/dist/esm/icons/funnel";
import Gamepad2Icon from "lucide-react-native/dist/esm/icons/gamepad-2";
import GaugeIcon from "lucide-react-native/dist/esm/icons/gauge";
import GemIcon from "lucide-react-native/dist/esm/icons/gem";
import GiftIcon from "lucide-react-native/dist/esm/icons/gift";
import GlobeIcon from "lucide-react-native/dist/esm/icons/globe";
import GripIcon from "lucide-react-native/dist/esm/icons/grip";
import HammerIcon from "lucide-react-native/dist/esm/icons/hammer";
import HandIcon from "lucide-react-native/dist/esm/icons/hand";
import HandCoinsIcon from "lucide-react-native/dist/esm/icons/hand-coins";
import HandshakeIcon from "lucide-react-native/dist/esm/icons/handshake";
import HardDriveIcon from "lucide-react-native/dist/esm/icons/hard-drive";
import HashIcon from "lucide-react-native/dist/esm/icons/hash";
import HeadingIcon from "lucide-react-native/dist/esm/icons/heading";
import HeadphonesIcon from "lucide-react-native/dist/esm/icons/headphones";
import HeartIcon from "lucide-react-native/dist/esm/icons/heart";
import HeartHandshakeIcon from "lucide-react-native/dist/esm/icons/heart-handshake";
import HeartOffIcon from "lucide-react-native/dist/esm/icons/heart-off";
import HexagonIcon from "lucide-react-native/dist/esm/icons/hexagon";
import HistoryIcon from "lucide-react-native/dist/esm/icons/history";
import HourglassIcon from "lucide-react-native/dist/esm/icons/hourglass";
import HouseIcon from "lucide-react-native/dist/esm/icons/house";
import IdCardIcon from "lucide-react-native/dist/esm/icons/id-card";
import ImageIcon from "lucide-react-native/dist/esm/icons/image";
import ImageDownIcon from "lucide-react-native/dist/esm/icons/image-down";
import ImagePlusIcon from "lucide-react-native/dist/esm/icons/image-plus";
import ImagesIcon from "lucide-react-native/dist/esm/icons/images";
import ImportIcon from "lucide-react-native/dist/esm/icons/import";
import InfoIcon from "lucide-react-native/dist/esm/icons/info";
import InstagramIcon from "lucide-react-native/dist/esm/icons/instagram";
import ItalicIcon from "lucide-react-native/dist/esm/icons/italic";
import KeyRoundIcon from "lucide-react-native/dist/esm/icons/key-round";
import LampIcon from "lucide-react-native/dist/esm/icons/lamp";
import LandmarkIcon from "lucide-react-native/dist/esm/icons/landmark";
import LanguagesIcon from "lucide-react-native/dist/esm/icons/languages";
import LayersIcon from "lucide-react-native/dist/esm/icons/layers";
import LayoutDashboardIcon from "lucide-react-native/dist/esm/icons/layout-dashboard";
import LayoutGridIcon from "lucide-react-native/dist/esm/icons/layout-grid";
import LifeBuoyIcon from "lucide-react-native/dist/esm/icons/life-buoy";
import LightbulbIcon from "lucide-react-native/dist/esm/icons/lightbulb";
import LinkIcon from "lucide-react-native/dist/esm/icons/link";
import Link2Icon from "lucide-react-native/dist/esm/icons/link-2";
import ListFilterIcon from "lucide-react-native/dist/esm/icons/list-filter";
import ListVideoIcon from "lucide-react-native/dist/esm/icons/list-video";
import LoaderIcon from "lucide-react-native/dist/esm/icons/loader";
import LockIcon from "lucide-react-native/dist/esm/icons/lock";
import LockOpenIcon from "lucide-react-native/dist/esm/icons/lock-open";
import LogInIcon from "lucide-react-native/dist/esm/icons/log-in";
import LogOutIcon from "lucide-react-native/dist/esm/icons/log-out";
import MailIcon from "lucide-react-native/dist/esm/icons/mail";
import MailOpenIcon from "lucide-react-native/dist/esm/icons/mail-open";
import MapIcon from "lucide-react-native/dist/esm/icons/map";
import MapPinIcon from "lucide-react-native/dist/esm/icons/map-pin";
import MaximizeIcon from "lucide-react-native/dist/esm/icons/maximize";
import Maximize2Icon from "lucide-react-native/dist/esm/icons/maximize-2";
import MegaphoneIcon from "lucide-react-native/dist/esm/icons/megaphone";
import MenuIcon from "lucide-react-native/dist/esm/icons/menu";
import MessageCircleIcon from "lucide-react-native/dist/esm/icons/message-circle";
import MessageCircleWarningIcon from "lucide-react-native/dist/esm/icons/message-circle-warning";
import MessageSquareIcon from "lucide-react-native/dist/esm/icons/message-square";
import MessageSquareTextIcon from "lucide-react-native/dist/esm/icons/message-square-text";
import MessagesSquareIcon from "lucide-react-native/dist/esm/icons/messages-square";
import MicIcon from "lucide-react-native/dist/esm/icons/mic";
import MicOffIcon from "lucide-react-native/dist/esm/icons/mic-off";
import MicVocalIcon from "lucide-react-native/dist/esm/icons/mic-vocal";
import MinimizeIcon from "lucide-react-native/dist/esm/icons/minimize";
import Minimize2Icon from "lucide-react-native/dist/esm/icons/minimize-2";
import MinusIcon from "lucide-react-native/dist/esm/icons/minus";
import MonitorIcon from "lucide-react-native/dist/esm/icons/monitor";
import MonitorPlayIcon from "lucide-react-native/dist/esm/icons/monitor-play";
import MonitorUpIcon from "lucide-react-native/dist/esm/icons/monitor-up";
import MoonIcon from "lucide-react-native/dist/esm/icons/moon";
import MoveIcon from "lucide-react-native/dist/esm/icons/move";
import MoveRightIcon from "lucide-react-native/dist/esm/icons/move-right";
import MoveVerticalIcon from "lucide-react-native/dist/esm/icons/move-vertical";
import MusicIcon from "lucide-react-native/dist/esm/icons/music";
import Music2Icon from "lucide-react-native/dist/esm/icons/music-2";
import NavigationIcon from "lucide-react-native/dist/esm/icons/navigation";
import NetworkIcon from "lucide-react-native/dist/esm/icons/network";
import PackageIcon from "lucide-react-native/dist/esm/icons/package";
import PaintBucketIcon from "lucide-react-native/dist/esm/icons/paint-bucket";
import PaletteIcon from "lucide-react-native/dist/esm/icons/palette";
import PaperclipIcon from "lucide-react-native/dist/esm/icons/paperclip";
import PauseIcon from "lucide-react-native/dist/esm/icons/pause";
import PenLineIcon from "lucide-react-native/dist/esm/icons/pen-line";
import PencilIcon from "lucide-react-native/dist/esm/icons/pencil";
import PhoneIcon from "lucide-react-native/dist/esm/icons/phone";
import PhoneOffIcon from "lucide-react-native/dist/esm/icons/phone-off";
import PictureInPicture2Icon from "lucide-react-native/dist/esm/icons/picture-in-picture-2";
import PinIcon from "lucide-react-native/dist/esm/icons/pin";
import PinOffIcon from "lucide-react-native/dist/esm/icons/pin-off";
import PlayIcon from "lucide-react-native/dist/esm/icons/play";
import PlusIcon from "lucide-react-native/dist/esm/icons/plus";
import QuoteIcon from "lucide-react-native/dist/esm/icons/quote";
import RadioIcon from "lucide-react-native/dist/esm/icons/radio";
import ReceiptIcon from "lucide-react-native/dist/esm/icons/receipt";
import RectangleHorizontalIcon from "lucide-react-native/dist/esm/icons/rectangle-horizontal";
import RectangleVerticalIcon from "lucide-react-native/dist/esm/icons/rectangle-vertical";
import Redo2Icon from "lucide-react-native/dist/esm/icons/redo-2";
import RefreshCwIcon from "lucide-react-native/dist/esm/icons/refresh-cw";
import RepeatIcon from "lucide-react-native/dist/esm/icons/repeat";
import Repeat2Icon from "lucide-react-native/dist/esm/icons/repeat-2";
import ReplyIcon from "lucide-react-native/dist/esm/icons/reply";
import RocketIcon from "lucide-react-native/dist/esm/icons/rocket";
import RotateCcwIcon from "lucide-react-native/dist/esm/icons/rotate-ccw";
import RotateCwIcon from "lucide-react-native/dist/esm/icons/rotate-cw";
import RulerIcon from "lucide-react-native/dist/esm/icons/ruler";
import SaveIcon from "lucide-react-native/dist/esm/icons/save";
import ScaleIcon from "lucide-react-native/dist/esm/icons/scale";
import ScanLineIcon from "lucide-react-native/dist/esm/icons/scan-line";
import ScissorsIcon from "lucide-react-native/dist/esm/icons/scissors";
import ScreenShareIcon from "lucide-react-native/dist/esm/icons/screen-share";
import ScrollIcon from "lucide-react-native/dist/esm/icons/scroll";
import SearchIcon from "lucide-react-native/dist/esm/icons/search";
import SendIcon from "lucide-react-native/dist/esm/icons/send";
import ServerIcon from "lucide-react-native/dist/esm/icons/server";
import SettingsIcon from "lucide-react-native/dist/esm/icons/settings";
import Settings2Icon from "lucide-react-native/dist/esm/icons/settings-2";
import ShapesIcon from "lucide-react-native/dist/esm/icons/shapes";
import ShareIcon from "lucide-react-native/dist/esm/icons/share";
import Share2Icon from "lucide-react-native/dist/esm/icons/share-2";
import ShieldIcon from "lucide-react-native/dist/esm/icons/shield";
import ShieldAlertIcon from "lucide-react-native/dist/esm/icons/shield-alert";
import ShieldCheckIcon from "lucide-react-native/dist/esm/icons/shield-check";
import ShieldOffIcon from "lucide-react-native/dist/esm/icons/shield-off";
import ShoppingBagIcon from "lucide-react-native/dist/esm/icons/shopping-bag";
import ShoppingCartIcon from "lucide-react-native/dist/esm/icons/shopping-cart";
import SlidersHorizontalIcon from "lucide-react-native/dist/esm/icons/sliders-horizontal";
import SmartphoneIcon from "lucide-react-native/dist/esm/icons/smartphone";
import SmileIcon from "lucide-react-native/dist/esm/icons/smile";
import SparklesIcon from "lucide-react-native/dist/esm/icons/sparkles";
import SpellCheckIcon from "lucide-react-native/dist/esm/icons/spell-check";
import SquareIcon from "lucide-react-native/dist/esm/icons/square";
import SquarePenIcon from "lucide-react-native/dist/esm/icons/square-pen";
import SquareRoundCornerIcon from "lucide-react-native/dist/esm/icons/square-round-corner";
import StampIcon from "lucide-react-native/dist/esm/icons/stamp";
import StarIcon from "lucide-react-native/dist/esm/icons/star";
import StoreIcon from "lucide-react-native/dist/esm/icons/store";
import SunIcon from "lucide-react-native/dist/esm/icons/sun";
import SunriseIcon from "lucide-react-native/dist/esm/icons/sunrise";
import TagIcon from "lucide-react-native/dist/esm/icons/tag";
import TargetIcon from "lucide-react-native/dist/esm/icons/target";
import TextIcon from "lucide-react-native/dist/esm/icons/text";
import ThumbsDownIcon from "lucide-react-native/dist/esm/icons/thumbs-down";
import ThumbsUpIcon from "lucide-react-native/dist/esm/icons/thumbs-up";
import TicketIcon from "lucide-react-native/dist/esm/icons/ticket";
import TimerIcon from "lucide-react-native/dist/esm/icons/timer";
import Trash2Icon from "lucide-react-native/dist/esm/icons/trash-2";
import TrendingDownIcon from "lucide-react-native/dist/esm/icons/trending-down";
import TrendingUpIcon from "lucide-react-native/dist/esm/icons/trending-up";
import TriangleIcon from "lucide-react-native/dist/esm/icons/triangle";
import TriangleAlertIcon from "lucide-react-native/dist/esm/icons/triangle-alert";
import TrophyIcon from "lucide-react-native/dist/esm/icons/trophy";
import TruckIcon from "lucide-react-native/dist/esm/icons/truck";
import TvIcon from "lucide-react-native/dist/esm/icons/tv";
import TwitchIcon from "lucide-react-native/dist/esm/icons/twitch";
import TwitterIcon from "lucide-react-native/dist/esm/icons/twitter";
import TypeIcon from "lucide-react-native/dist/esm/icons/type";
import UnderlineIcon from "lucide-react-native/dist/esm/icons/underline";
import UndoIcon from "lucide-react-native/dist/esm/icons/undo";
import Undo2Icon from "lucide-react-native/dist/esm/icons/undo-2";
import UploadIcon from "lucide-react-native/dist/esm/icons/upload";
import UserIcon from "lucide-react-native/dist/esm/icons/user";
import UserCheckIcon from "lucide-react-native/dist/esm/icons/user-check";
import UserMinusIcon from "lucide-react-native/dist/esm/icons/user-minus";
import UserPlusIcon from "lucide-react-native/dist/esm/icons/user-plus";
import UserRoundIcon from "lucide-react-native/dist/esm/icons/user-round";
import UsersIcon from "lucide-react-native/dist/esm/icons/users";
import UsersRoundIcon from "lucide-react-native/dist/esm/icons/users-round";
import VaultIcon from "lucide-react-native/dist/esm/icons/vault";
import VideoIcon from "lucide-react-native/dist/esm/icons/video";
import VideoOffIcon from "lucide-react-native/dist/esm/icons/video-off";
import ViewIcon from "lucide-react-native/dist/esm/icons/view";
import Volume1Icon from "lucide-react-native/dist/esm/icons/volume-1";
import Volume2Icon from "lucide-react-native/dist/esm/icons/volume-2";
import VolumeXIcon from "lucide-react-native/dist/esm/icons/volume-x";
import VoteIcon from "lucide-react-native/dist/esm/icons/vote";
import WalletIcon from "lucide-react-native/dist/esm/icons/wallet";
import WandIcon from "lucide-react-native/dist/esm/icons/wand";
import WandSparklesIcon from "lucide-react-native/dist/esm/icons/wand-sparkles";
import WifiOffIcon from "lucide-react-native/dist/esm/icons/wifi-off";
import WrenchIcon from "lucide-react-native/dist/esm/icons/wrench";
import XIcon from "lucide-react-native/dist/esm/icons/x";
import ZapIcon from "lucide-react-native/dist/esm/icons/zap";
import ZoomInIcon from "lucide-react-native/dist/esm/icons/zoom-in";
import ZoomOutIcon from "lucide-react-native/dist/esm/icons/zoom-out";

export const iconRegistry = {
  Activity: ActivityIcon,
  AlignCenter: AlignCenterIcon,
  AlignLeft: AlignLeftIcon,
  AlignRight: AlignRightIcon,
  Anchor: AnchorIcon,
  Apple: AppleIcon,
  Archive: ArchiveIcon,
  ArrowDown: ArrowDownIcon,
  ArrowDownLeft: ArrowDownLeftIcon,
  ArrowDownToLine: ArrowDownToLineIcon,
  ArrowLeft: ArrowLeftIcon,
  ArrowLeftRight: ArrowLeftRightIcon,
  ArrowRight: ArrowRightIcon,
  ArrowUp: ArrowUpIcon,
  ArrowUpDown: ArrowUpDownIcon,
  ArrowUpLeft: ArrowUpLeftIcon,
  ArrowUpRight: ArrowUpRightIcon,
  ArrowUpToLine: ArrowUpToLineIcon,
  AtSign: AtSignIcon,
  Atom: AtomIcon,
  AudioLines: AudioLinesIcon,
  Award: AwardIcon,
  Baby: BabyIcon,
  Ban: BanIcon,
  Banknote: BanknoteIcon,
  Bell: BellIcon,
  BellOff: BellOffIcon,
  BellRing: BellRingIcon,
  Bitcoin: BitcoinIcon,
  Blend: BlendIcon,
  Bold: BoldIcon,
  BookOpen: BookOpenIcon,
  Bookmark: BookmarkIcon,
  Bot: BotIcon,
  Briefcase: BriefcaseIcon,
  Bug: BugIcon,
  Calendar: CalendarIcon,
  CalendarCheck: CalendarCheckIcon,
  CalendarClock: CalendarClockIcon,
  CalendarDays: CalendarDaysIcon,
  Camera: CameraIcon,
  CaseUpper: CaseUpperIcon,
  ChartBarBig: ChartBarBigIcon,
  ChartColumn: ChartColumnIcon,
  ChartNoAxesColumn: ChartNoAxesColumnIcon,
  ChartNoAxesCombined: ChartNoAxesCombinedIcon,
  ChartPie: ChartPieIcon,
  Check: CheckIcon,
  CheckCheck: CheckCheckIcon,
  ChevronDown: ChevronDownIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  ChevronUp: ChevronUpIcon,
  ChevronsRight: ChevronsRightIcon,
  Circle: CircleIcon,
  CircleAlert: CircleAlertIcon,
  CircleCheck: CircleCheckIcon,
  CircleCheckBig: CircleCheckBigIcon,
  CircleMinus: CircleMinusIcon,
  CirclePlay: CirclePlayIcon,
  CircleX: CircleXIcon,
  Clapperboard: ClapperboardIcon,
  Clipboard: ClipboardIcon,
  ClipboardPaste: ClipboardPasteIcon,
  Clock: ClockIcon,
  CloudUpload: CloudUploadIcon,
  Coins: CoinsIcon,
  Compass: CompassIcon,
  Component: ComponentIcon,
  Copy: CopyIcon,
  CornerDownLeft: CornerDownLeftIcon,
  Cpu: CpuIcon,
  CreditCard: CreditCardIcon,
  Crop: CropIcon,
  Crosshair: CrosshairIcon,
  Crown: CrownIcon,
  Delete: DeleteIcon,
  Disc3: Disc3Icon,
  DollarSign: DollarSignIcon,
  Download: DownloadIcon,
  Ellipsis: EllipsisIcon,
  EllipsisVertical: EllipsisVerticalIcon,
  Expand: ExpandIcon,
  ExternalLink: ExternalLinkIcon,
  Eye: EyeIcon,
  EyeOff: EyeOffIcon,
  Facebook: FacebookIcon,
  FastForward: FastForwardIcon,
  File: FileIcon,
  FileText: FileTextIcon,
  Film: FilmIcon,
  Fingerprint: FingerprintIcon,
  Flag: FlagIcon,
  Flame: FlameIcon,
  FlipHorizontal2: FlipHorizontal2Icon,
  FlipVertical2: FlipVertical2Icon,
  Folder: FolderIcon,
  FolderInput: FolderInputIcon,
  FolderPlus: FolderPlusIcon,
  Forward: ForwardIcon,
  Fuel: FuelIcon,
  Fullscreen: FullscreenIcon,
  Funnel: FunnelIcon,
  Gamepad2: Gamepad2Icon,
  Gauge: GaugeIcon,
  Gem: GemIcon,
  Gift: GiftIcon,
  Globe: GlobeIcon,
  Grip: GripIcon,
  Hammer: HammerIcon,
  Hand: HandIcon,
  HandCoins: HandCoinsIcon,
  Handshake: HandshakeIcon,
  HardDrive: HardDriveIcon,
  Hash: HashIcon,
  Heading: HeadingIcon,
  Headphones: HeadphonesIcon,
  Heart: HeartIcon,
  HeartHandshake: HeartHandshakeIcon,
  HeartOff: HeartOffIcon,
  Hexagon: HexagonIcon,
  History: HistoryIcon,
  Hourglass: HourglassIcon,
  House: HouseIcon,
  IdCard: IdCardIcon,
  Image: ImageIcon,
  ImageDown: ImageDownIcon,
  ImagePlus: ImagePlusIcon,
  Images: ImagesIcon,
  Import: ImportIcon,
  Info: InfoIcon,
  Instagram: InstagramIcon,
  Italic: ItalicIcon,
  KeyRound: KeyRoundIcon,
  Lamp: LampIcon,
  Landmark: LandmarkIcon,
  Languages: LanguagesIcon,
  Layers: LayersIcon,
  LayoutDashboard: LayoutDashboardIcon,
  LayoutGrid: LayoutGridIcon,
  LifeBuoy: LifeBuoyIcon,
  Lightbulb: LightbulbIcon,
  Link: LinkIcon,
  Link2: Link2Icon,
  ListFilter: ListFilterIcon,
  ListVideo: ListVideoIcon,
  Loader: LoaderIcon,
  Lock: LockIcon,
  LockOpen: LockOpenIcon,
  LogIn: LogInIcon,
  LogOut: LogOutIcon,
  Mail: MailIcon,
  MailOpen: MailOpenIcon,
  Map: MapIcon,
  MapPin: MapPinIcon,
  Maximize: MaximizeIcon,
  Maximize2: Maximize2Icon,
  Megaphone: MegaphoneIcon,
  Menu: MenuIcon,
  MessageCircle: MessageCircleIcon,
  MessageCircleWarning: MessageCircleWarningIcon,
  MessageSquare: MessageSquareIcon,
  MessageSquareText: MessageSquareTextIcon,
  MessagesSquare: MessagesSquareIcon,
  Mic: MicIcon,
  MicOff: MicOffIcon,
  MicVocal: MicVocalIcon,
  Minimize: MinimizeIcon,
  Minimize2: Minimize2Icon,
  Minus: MinusIcon,
  Monitor: MonitorIcon,
  MonitorPlay: MonitorPlayIcon,
  MonitorUp: MonitorUpIcon,
  Moon: MoonIcon,
  Move: MoveIcon,
  MoveRight: MoveRightIcon,
  MoveVertical: MoveVerticalIcon,
  Music: MusicIcon,
  Music2: Music2Icon,
  Navigation: NavigationIcon,
  Network: NetworkIcon,
  Package: PackageIcon,
  PaintBucket: PaintBucketIcon,
  Palette: PaletteIcon,
  Paperclip: PaperclipIcon,
  Pause: PauseIcon,
  PenLine: PenLineIcon,
  Pencil: PencilIcon,
  Phone: PhoneIcon,
  PhoneOff: PhoneOffIcon,
  PictureInPicture2: PictureInPicture2Icon,
  Pin: PinIcon,
  PinOff: PinOffIcon,
  Play: PlayIcon,
  Plus: PlusIcon,
  Quote: QuoteIcon,
  Radio: RadioIcon,
  Receipt: ReceiptIcon,
  RectangleHorizontal: RectangleHorizontalIcon,
  RectangleVertical: RectangleVerticalIcon,
  Redo2: Redo2Icon,
  RefreshCw: RefreshCwIcon,
  Repeat: RepeatIcon,
  Repeat2: Repeat2Icon,
  Reply: ReplyIcon,
  Rocket: RocketIcon,
  RotateCcw: RotateCcwIcon,
  RotateCw: RotateCwIcon,
  Ruler: RulerIcon,
  Save: SaveIcon,
  Scale: ScaleIcon,
  ScanLine: ScanLineIcon,
  Scissors: ScissorsIcon,
  ScreenShare: ScreenShareIcon,
  Scroll: ScrollIcon,
  Search: SearchIcon,
  Send: SendIcon,
  Server: ServerIcon,
  Settings: SettingsIcon,
  Settings2: Settings2Icon,
  Shapes: ShapesIcon,
  Share: ShareIcon,
  Share2: Share2Icon,
  Shield: ShieldIcon,
  ShieldAlert: ShieldAlertIcon,
  ShieldCheck: ShieldCheckIcon,
  ShieldOff: ShieldOffIcon,
  ShoppingBag: ShoppingBagIcon,
  ShoppingCart: ShoppingCartIcon,
  SlidersHorizontal: SlidersHorizontalIcon,
  Smartphone: SmartphoneIcon,
  Smile: SmileIcon,
  Sparkles: SparklesIcon,
  SpellCheck: SpellCheckIcon,
  Square: SquareIcon,
  SquarePen: SquarePenIcon,
  SquareRoundCorner: SquareRoundCornerIcon,
  Stamp: StampIcon,
  Star: StarIcon,
  Store: StoreIcon,
  Sun: SunIcon,
  Sunrise: SunriseIcon,
  Tag: TagIcon,
  Target: TargetIcon,
  Text: TextIcon,
  ThumbsDown: ThumbsDownIcon,
  ThumbsUp: ThumbsUpIcon,
  Ticket: TicketIcon,
  Timer: TimerIcon,
  Trash2: Trash2Icon,
  TrendingDown: TrendingDownIcon,
  TrendingUp: TrendingUpIcon,
  Triangle: TriangleIcon,
  TriangleAlert: TriangleAlertIcon,
  Trophy: TrophyIcon,
  Truck: TruckIcon,
  Tv: TvIcon,
  Twitch: TwitchIcon,
  Twitter: TwitterIcon,
  Type: TypeIcon,
  Underline: UnderlineIcon,
  Undo: UndoIcon,
  Undo2: Undo2Icon,
  Upload: UploadIcon,
  User: UserIcon,
  UserCheck: UserCheckIcon,
  UserMinus: UserMinusIcon,
  UserPlus: UserPlusIcon,
  UserRound: UserRoundIcon,
  Users: UsersIcon,
  UsersRound: UsersRoundIcon,
  Vault: VaultIcon,
  Video: VideoIcon,
  VideoOff: VideoOffIcon,
  View: ViewIcon,
  Volume1: Volume1Icon,
  Volume2: Volume2Icon,
  VolumeX: VolumeXIcon,
  Vote: VoteIcon,
  Wallet: WalletIcon,
  Wand: WandIcon,
  WandSparkles: WandSparklesIcon,
  WifiOff: WifiOffIcon,
  Wrench: WrenchIcon,
  X: XIcon,
  Zap: ZapIcon,
  ZoomIn: ZoomInIcon,
  ZoomOut: ZoomOutIcon,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;
