import { REOWN_PROJECT_ID, API_URL, APP_ENV, INFURA_KEY, WEB3AUTH_CLIENT_ID, CDN_BASE_URL, APP_ORIGIN } from '@env';

const env = {
  REOWN_PROJECT_ID: REOWN_PROJECT_ID,
  API_URL: API_URL,
  APP_ENV: APP_ENV || "development",
  INFURA_KEY: INFURA_KEY,
  WEB3AUTH_CLIENT_ID: WEB3AUTH_CLIENT_ID,
  CDN_BASE_URL: CDN_BASE_URL,
  APP_ORIGIN: APP_ORIGIN || "https://dehub.io",
};

console.log("REOWN_PROJECT_ID:", REOWN_PROJECT_ID);
export default env;