import {
  REOWN_PROJECT_ID,
  API_URL,
  APP_ENV,
  INFURA_KEY,
  ALCHEMY_API_KEY,
  WEB3AUTH_CLIENT_ID,
  WEB3AUTH_APPLE_VERIFIER,
  CDN_BASE_URL,
  APP_ORIGIN,
  WEBSOCKET_URL,
  LIVEPEER_API_KEY,
  DEBUG,
  AUTH_PROVIDER,
  TENOR_API_KEY,
  PIMLICO_API_KEY,
  STRIPE_PUBLISHABLE_KEY,
  LEGACY_APP_ORIGIN,
  SUPABASE_EDGE_BASE_URL,
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  AGORA_APP_ID,
} from "@env";
import { createLogger } from "../libs/logger";

const env = {
  REOWN_PROJECT_ID: REOWN_PROJECT_ID,
  API_URL: API_URL,
  // API_URL: "http://192.168.1.233:9015/api",
  // API_URL: "https://api.dehub.io/api",
  APP_ENV: APP_ENV || "development",
  INFURA_KEY: INFURA_KEY,
  ALCHEMY_API_KEY: ALCHEMY_API_KEY,
  WEB3AUTH_CLIENT_ID: WEB3AUTH_CLIENT_ID,
  // Name of the custom JWT verifier that validates Apple's identity tokens.
  // Unset means the Apple button doesn't render.
  WEB3AUTH_APPLE_VERIFIER: WEB3AUTH_APPLE_VERIFIER || "",
  CDN_BASE_URL: CDN_BASE_URL,
  APP_ORIGIN: APP_ORIGIN || "https://dehub.io",
  WEBSOCKET_URL:
    WEBSOCKET_URL || API_URL?.replace(/\/$/, "") || "https://api.dehub.io",
  // WEBSOCKET_URL: "http://192.168.1.233:9015",
  LIVEPEER_API_KEY: LIVEPEER_API_KEY,
  DEBUG: DEBUG,
  AUTH_PROVIDER: AUTH_PROVIDER,
  TENOR_API_KEY: TENOR_API_KEY,
  PIMLICO_API_KEY: PIMLICO_API_KEY,
  STRIPE_PUBLISHABLE_KEY: STRIPE_PUBLISHABLE_KEY,
  LEGACY_APP_ORIGIN: LEGACY_APP_ORIGIN,
  SUPABASE_EDGE_BASE_URL: SUPABASE_EDGE_BASE_URL,
  SUPABASE_URL: SUPABASE_URL || "https://aigxuutjaqsywioxjefr.supabase.co",
  SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY || "",
  AGORA_APP_ID: AGORA_APP_ID || "",
};

const log = createLogger('env');
log.debug('API_URL:', API_URL);
export default env;
