plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'io.dehub'
version = '1.0.0'

android {
  namespace 'io.dehub.screencapture'
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
  testImplementation 'junit:junit:4.13.2'
}
